---
# Number of pods to create:
replicas: 2
# For the pod distruption budget, default is replicas - 1:
minAvailableReplicas:

# The secret (must already exist in the namespace) used to pull images:
pullSecret: "dockerconfigjson-github-com"

image:
tag:

# Default Spring Profile:
springProfile: "kubernetes"

# It is possible to use a normal yaml tree here, for example:
# root:
#   node1: 1
#   node2: 2
#
# If there is a lot of config, it is useful to use the helm function --set-file.
config:

# It is possible to use a normal yaml tree here, for example:
# root:
#   node1: 1
#   node2: 2
#
# If there is a lot of secrets, it is useful to use the helm function --set-file.
secrets:

# Any roles the generated service account should be bound to:
roles: []

# If the service should be exposed outside the cluster by Traefik, specify the rule:
application_traefik_rule:

application_web_port: 8080
application_actuator_port: 8180

prometheus_enabled: "true"
prometheus_port: 8180
prometheus_path: "/actuator/prometheus"

memory_request: "256Mi"
memory_limit: "1024Mi"

cpu_request: "0.2"
cpu_limit: "2.5"