---
# Number of pods to create:
replicas: 2

# For the pod disruption budget, default is (replicas - 1):
minAvailableReplicas:

# Set to false to avoid creating PodDisruptionBudget for pods
createPodDisruptionBudget: "true"

# Name to use in kubernetes resources, must be unique inside a namespace
resourceName: frontend

# Container image ref for pods
image:

# Container image tag for pods
tag:

# Annotations to put on the Deployment:
deploymentAnnotations:
  # dsb-norge org. in Snyk
  orgs.k8s.snyk.io/v1: 3c6b0e2e-36a2-4c0e-93c8-3ba8c87dd75d

# Annotations to put on every pod:
# Usage when applying with values.yaml
# podAnnotations:
#   my-custom-key: "my custom value"                  # add custom annotation
#   co.elastic.logs/json.message_key: "my_override"   # override a default
# To remove all defaults and not specify any annotations:
# podAnnotations: null                                # Note that using empty map {} will not work
podAnnotations:
  apparmor.security.beta.kubernetes.io/pod: "runtime/default"
  no.dsb-norge.filebeat/autodiscover-template: "nginx"

# It is possible to use a normal yaml tree here, for example:
# root:
#   node1: 1
#   node2: 2
#
# If there is a lot of config, it is useful to use the helm function --set-file.
config: {}

# Reference secrets that are mounted on the pod:
secretRefs: {}

# Reference configMaps that are mounted on the pod:
configMapRefs: {}

# bring your own volumes
extraVolumes: []
# - csi:
#     driver: secrets-store.csi.k8s.io
#     readOnly: true
#     volumeAttributes:
#       secretProviderClass: "my-key-vault-from-azure" # created elsewhere
#   name: "my-key-vault-volume"

# bring your own volume mounts
extraVolumeMounts: []
# - name: my-key-vault-volume
#   mountPath: /mnt/dsb/key-vault
#   readOnly: true

# Hostname must be provided if Ingress should be enabled.
ingress_host:
ingress_path: /

# If there are multiple hostnames for the given service
#
# ingress:
#   - host: farligeprodukter.no
#   - host: www.farligeprodukter.no
#     path: /something
ingress:

# Port number for nginx
port: 8080

memory_request: "128Mi"
memory_limit: "256Mi"

cpu_request: "50m"
cpu_limit: "100m"

prometheus_enabled: "true"
mgmt_image: "nginx/nginx-prometheus-exporter"
mgmt_tag: "0.10.0"
mgmt_memory_request: "64Mi"
mgmt_memory_limit: "128Mi"
mgmt_cpu_request: "10m"
mgmt_cpu_limit: "50m"

proxy_read_timeout: "120"
proxy_connect_timeout: "120"
proxy_send_timeout: "120"

# Values giving recommended lables to resources. making them easier
# to recognize in different dashboard applications
#
# dashboard:
#   name:       The name of the application - Example: mysql - Default: Release Name
#   component:  The component within the architecture - Example: database - Default: API
#   partOf:     The name of a higher level application this one is part of - Example: wordpress - Default Release Name
dashboard: {}

websocket:
  enabled: false
  path: /

# The value which will populate the LANG environment variable in the pod
lang: "en_US.UTF-8"
