apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Values.resourceName }}.pdb"
spec:
  minAvailable: {{ default ( sub .Values.replicas 1 ) .Values.minAvailableReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.resourceName }}
