apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resourceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart-name: "{{ .Chart.Name }}"
    chart-version: "{{ .Chart.Version }}"
    app: "{{ .Values.resourceName }}-service"
spec:
  ports:
    - name: web
      port: {{ .Values.port }}
    - name: status
      port: 8180
    {{- if (not (eq (toString .Values.prometheus_enabled) "false")) }}
    - name: prometheus
      port: 9113
    {{- end }}
  selector:
    app: {{ .Values.resourceName }}
