apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resourceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart-name: "{{ .Chart.Name }}"
    chart-version: "{{ .Chart.Version }}"
spec:
  ports:
    - name: web
      port: {{ .Values.port }}
  selector:
    app: {{ .Values.resourceName }}
