{{- if (not (eq (toString .Values.prometheus_enabled) "false")) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-monitor
  labels:
    release: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Values.resourceName }}-service
  endpoints:
    - port: web
      interval: 30s
{{- end }}
