---
replicas: 2

image: "dsbacr.azurecr.io/dsb-norge/test-application"
tag: "latest"

# Kind cluster should not attempt to pull as it's missing docker credentials
# The Kubernetes default pull policy is IfNotPresent unless the image tag is :latest
# or omitted (and implicitly :latest) in which case the default policy is Always.
imagePullPolicy: "Never"

ingress_host: "example.com"

dashboard:
  name: "kind-k8s-test"
  component: "backend-api"
  partOf: "verification-stuff"

rbac:
  enabled: true
  roles:
    podPermission:
      apiGroups:
        - ""
        - apps
      resources:
        - pods
        - deployments
      verbs:
        - list
        - watch
        - get
    nodePermissions:
      apiGroups:
        - ""
      resources:
        - nodes
      verbs:
        - list
        - get
