{{ if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Values.config }}
    {{ $key | quote }}: {{ $val | toString | quote }}
  {{- end }}
{{ end }}