{{ if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key | quote }}: {{ $val | toString | b64enc }}
  {{- end }}
{{ end }}