{{ if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
{{ template "envifyB64" (list "" .Values.secrets) }}
{{ end }}