{{- $release_name := .Release.Name }}
{{- $release_namespace := .Release.Namespace }}

{{- range $name, $value := .Values.certificates }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}-info
  namespace: {{ $release_namespace }}
spec:
  backendType: azureKeyVault
  keyVaultName: {{ $value.key_vault.name  }}
  data:
    - key: {{ quote $value.key_vault.keystore_password_ref }}
      name: {{ regexReplaceAll "-" $name "_" | upper }}_CERTIFICATE_KEYSTORE
    - key: {{ quote $value.key_vault.keystore_alias_ref }}
      name: {{ regexReplaceAll "-" $name "_" | upper }}_CERTIFICATE_ALIAS
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}-file
  namespace: {{ $release_namespace }}
spec:
  backendType: azureKeyVault
  keyVaultName: {{ $value.key_vault.name  }}
  data:
    - key: {{ quote $value.key_vault.keystore_ref }}
      name: {{ quote $value.fileName }}
      isBinary: {{ default "true" $value.isBinary }}
{{- end }}