{{- if .Values.ingress_host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Must be a valid DNS name:
  name: "{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.dashboard.name | default .Release.Name }}
    app.kubernetes.io/component: {{ .Values.dashboard.component | default "API" }}
    app.kubernetes.io/part-of: {{ .Values.dashboard.partOf | default .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/created-by: {{ .Values.dashboard.createdBy | default .Release.Service }}
    helm.sh/chart-name: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version | replace "+" "_" }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  rules:
    - host: "{{ .Values.ingress_host }}"
      http:
        paths:
          - path: "{{ .Values.ingress_path }}"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}"
                port:
                  number: {{ .Values.application_web_port }}
{{- end -}}
