{{- if (not (eq (toString .Values.createPodDisruptionBudget) "false")) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}.pdb
spec:
  minAvailable: {{ default ( sub .Values.replicas 1 ) .Values.minAvailableReplicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
{{- end }}