{{- if .Values.cache.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # This will generate a new 16-character password on every helm upgrade.
  password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}