{{- if .Values.cache.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # This will generate a new 16-character password on every helm upgrade.
  # The cache.password should not be used. It's to allow testing to pass with static pw
  password: {{ .Values.cache.password | default (randAlphaNum 16) | b64enc | quote }}
{{- end }}