---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-app
  {{- if empty .Values.azureWorkloadIdentity.clientId | not }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.azureWorkloadIdentity.clientId | quote }}
  {{- end }}
...