name: 'Release the chart'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (SemVer)'
        required: true

env:
  CHART_NAME: 'dsb-spring-boot'
  # Needed to deploy helm chart as oci bundle:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  set-variables:
    name: Release the chart
    runs-on: self-hosted

    steps:
      - name: Checkout working branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update chart version in Chart.yaml
        run: "sed -i 's/^version:.*/version: ${{ github.event.inputs.version }}/' ${{ env.CHART_NAME }}/Chart.yaml"

      - name: Run linting
        run: helm lint dsb-spring-boot

      - name: Login to registry
        run: echo  ${{ secrets.AZ_CR_SECRET }} | helm registry login ${{ secrets.AZ_CR_SERVER }} --username ${{ secrets.AZ_CR_USER }} --password-stdin

      - name: Save helm chart
        run: helm chart save ./dsb-spring-boot ${{ secrets.AZ_CR_SERVER }}/helm/${{ env.CHART_NAME }}:${{ github.event.inputs.version }}

      - name: Push helm chart
        run: helm chart push ${{ secrets.AZ_CR_SERVER }}/helm/${{ env.CHART_NAME }}:${{ github.event.inputs.version }}
