name: 'Release the charts'

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Workspace cleanup
        run: rm -rf ${{ github.workspace }} && mkdir ${{ github.workspace }}

      - name: Checkout working branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run linting
        run: helm lint charts/*

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release chart
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
