name: 'Verify PR'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout working branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      #- name: Run chart-testing (lint)
      #  run: ct lint --all

      - name: Create kind cluster
        uses: helm/kind-action@v1.1.0
        with:
          config: kind-cluster-config.yaml
        env:
          GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}

      - name: Run chart-testing (install)
        run: ct install --all
