name: "Verify PR"

on:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for Azure password-less auth
      contents: read # required for actions/checkout

    steps:
      - name: Workspace cleanup
        run: rm -rf ${{ github.workspace }} && mkdir ${{ github.workspace }}

      - name: Checkout working branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.11.3

      - name: Run linting (helm)
        run: helm lint charts/*

      - name: Log into Azure
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.REPO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REPO_AZURE_SUBSCRIPTION_ID }} # ss5, subscription where the registry resides
          client-id: ${{ secrets.REPO_ACR_SERVICE_PRINCIPAL_CLIENT_ID }} # entra id spn "uai-app-platform-cm-helm-charts-image-puller-wszr"

      - name: Log into azure container registry (ACR)
        run: |
          az acr login --name dsbacr.azurecr.io

      - name: Run Helm Unittests (exclude python chart)
        run: docker run --rm --name unittest --volume "$(pwd)":/apps dsbacr.azurecr.io/cache/docker-io/helmunittest/helm-unittest charts/dsb-nginx-frontend charts/dsb-spring-boot charts/dsb-spring-boot-job

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run linting (ct) - include only supported charts
        run: ct lint --charts charts/dsb-nginx-frontend charts/dsb-spring-boot charts/dsb-spring-boot-job --config .ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          config: kind-cluster-config.yaml
        env:
          GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}

      - name: Load custom test application image
        run: |
          # Make image(s) available to kind cluster as it has no pullSecrets
          # K8s defaults to always pull if tag is "latest", this is prevented by having
          # 'imagePullPolicy: "Never"' in charts/*/ci/*-values.yaml
          docker pull dsbacr.azurecr.io/dsb-norge/test-application:latest
          kind load --name chart-testing docker-image dsbacr.azurecr.io/dsb-norge/test-application:latest
          docker pull dsbacr.azurecr.io/dsb-norge/dsb-mssql-server:2019-latest
          kind load --name chart-testing docker-image dsbacr.azurecr.io/dsb-norge/dsb-mssql-server:2019-latest
          # must match the image in empty-nginx-values.yaml
          docker pull dsbacr.azurecr.io/cache/docker-io/nginxinc/nginx-unprivileged:1.20-alpine
          kind load --name chart-testing docker-image dsbacr.azurecr.io/cache/docker-io/nginxinc/nginx-unprivileged:1.20-alpine

      - name: Run chart-testing (install) - include only supported charts
        run: ct install --charts charts/dsb-nginx-frontend charts/dsb-spring-boot charts/dsb-spring-boot-job --config .ct.yaml
